# Generated by Django 4.0.2 on 2022-04-14 19:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otpmodel',
            name='id',
        ),
        migrations.AlterField(
            model_name='otpmodel',
            name='otp_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
