# Generated by Django 4.0.2 on 2022-04-15 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otpmodel',
            old_name='updated_at',
            new_name='expired_at',
        ),
    ]
