# Generated by Django 4.0.2 on 2022-05-04 13:20

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('course_code', models.CharField(max_length=10)),
                ('course_title', models.CharField(max_length=50)),
                ('credit', models.FloatField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('faculty_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('initials', models.CharField(max_length=10)),
                ('profile_picture', models.ImageField(default='male_default.svg', upload_to='profile_pics')),
                ('gender', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('(male|female|other)')])),
                ('username', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('grade', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('grade_point', models.FloatField()),
                ('maximum', models.FloatField()),
                ('minimum', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('section_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('section_no', models.PositiveIntegerField(default=1)),
                ('section_capacity', models.PositiveIntegerField(default=0)),
                ('total_students', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='advising_portal.course')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='section_creator', to=settings.AUTH_USER_MODEL)),
                ('instructor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='advising_portal.faculty')),
            ],
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('time_slot_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('day', models.CharField(max_length=10)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='WeekSlot',
            fields=[
                ('routine_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('profile_picture', models.ImageField(default='male_default.svg', upload_to='profile_pics')),
                ('gender', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('(male|female|other)')])),
                ('advisor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='advising_portal.faculty')),
                ('username', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('semester_id', models.AutoField(primary_key=True, serialize=False)),
                ('semester_name', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('(Spring|Summer|Fall)\\-[0-9]{4}')])),
                ('semester_starts_at', models.DateField()),
                ('semester_ends_at', models.DateField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(null=True)),
                ('advising_status', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('add_drop_status', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='semester_creator', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='semester_updater', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SectionsRequested',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('reason', models.TextField()),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='advising_portal.faculty')),
                ('section', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='advising_portal.section')),
                ('semester', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='advising_portal.semester')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advising_portal.student')),
            ],
        ),
        migrations.AddField(
            model_name='section',
            name='routine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='advising_portal.weekslot'),
        ),
        migrations.AddField(
            model_name='section',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='section_updater', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('routine_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advising_portal.weekslot')),
                ('time_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advising_portal.timeslot')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('department_name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CoursesTaken',
            fields=[
                ('course_record_id', models.AutoField(primary_key=True, serialize=False)),
                ('grade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='advising_portal.grade')),
                ('section', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='advising_portal.section')),
                ('semester', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='advising_portal.semester')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advising_portal.student')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='advising_portal.department'),
        ),
        migrations.AddField(
            model_name='course',
            name='prerequisite_course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='advising_portal.course'),
        ),
    ]
