# Generated by Django 4.0.2 on 2022-03-22 17:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('advising_portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('course_code', models.CharField(max_length=10)),
                ('course_title', models.TextField()),
                ('credit', models.FloatField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CoursesTaken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('department_name', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('faculty_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('initials', models.TextField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RoutineSlot',
            fields=[
                ('routine_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('section_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advising_portal.course')),
                ('instructor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advising_portal.faculty')),
                ('routine_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advising_portal.routineslot')),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('semester_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('semester_starts_on', models.DateField()),
                ('semester_ends_on', models.DateField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('advisor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='advising_portal.faculty')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('time_slot_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('day', models.TextField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='Courses',
        ),
        migrations.AddField(
            model_name='routineslot',
            name='time_slot_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='advising_portal.timeslot'),
        ),
        migrations.AddField(
            model_name='coursestaken',
            name='section_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='advising_portal.section'),
        ),
        migrations.AddField(
            model_name='coursestaken',
            name='semester_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='advising_portal.semester'),
        ),
        migrations.AddField(
            model_name='coursestaken',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advising_portal.student'),
        ),
        migrations.AddField(
            model_name='course',
            name='department_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='advising_portal.department'),
        ),
        migrations.AddField(
            model_name='course',
            name='prerequisite_course_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='advising_portal.course'),
        ),
    ]
