# Generated by Django 4.0.3 on 2022-04-22 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advising_portal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='semester',
            old_name='semester_ends_on',
            new_name='semester_ends_at',
        ),
        migrations.RenameField(
            model_name='semester',
            old_name='semester_starts_on',
            new_name='semester_starts_at',
        ),
        migrations.AddField(
            model_name='semester',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
