# Generated by Django 4.0.2 on 2022-05-14 13:40

import advising_portal.models
import datetime
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advising_portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursestaken',
            name='added_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 14, 19, 40, 28, 936667)),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='profile_picture',
            field=models.ImageField(default='default.jpg', storage=django.core.files.storage.FileSystemStorage(base_url='/media/profile_pictures/', location='C:\\Users\\Zubair\\PycharmProjects\\django_project\\media/profile_pictures/'), upload_to=advising_portal.models.image_directory_path),
        ),
        migrations.AlterField(
            model_name='sectionsrequested',
            name='requested_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 14, 19, 40, 28, 936667)),
        ),
        migrations.AlterField(
            model_name='student',
            name='profile_picture',
            field=models.ImageField(default='default.jpg', storage=django.core.files.storage.FileSystemStorage(base_url='/media/profile_pictures/', location='C:\\Users\\Zubair\\PycharmProjects\\django_project\\media/profile_pictures/'), upload_to=advising_portal.models.image_directory_path),
        ),
    ]
