# Generated by Django 4.0.2 on 2022-03-25 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advising_portal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routineslot',
            name='routine',
        ),
        migrations.RemoveField(
            model_name='routineslot',
            name='time_slot',
        ),
        migrations.AlterField(
            model_name='routineslot',
            name='routine_id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='RoutineAndTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('routine_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advising_portal.routineslot')),
                ('time_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advising_portal.timeslot')),
            ],
        ),
    ]
