# Generated by Django 4.0.2 on 2022-03-22 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advising_portal', '0002_course_coursestaken_department_faculty_routineslot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='section_capacity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='section',
            name='section_no',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='section',
            name='total_students',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='day',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
