# Generated by Django 4.0.2 on 2022-03-22 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advising_portal', '0003_section_section_capacity_section_section_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='prerequisite_course_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='advising_portal.course'),
        ),
    ]
