# Generated by Django 4.0.2 on 2022-03-22 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advising_portal', '0004_alter_course_prerequisite_course_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routineslot',
            name='time_slot_id',
        ),
        migrations.AddField(
            model_name='routineslot',
            name='time_slot_id',
            field=models.ManyToManyField(to='advising_portal.TimeSlot'),
        ),
    ]
