# Generated by Django 4.0.2 on 2022-03-22 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advising_portal', '0005_remove_routineslot_time_slot_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routineslot',
            name='time_slot_id',
        ),
        migrations.AddField(
            model_name='routineslot',
            name='time_slot_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='advising_portal.timeslot'),
        ),
    ]
