# Generated by Django 4.0.2 on 2022-03-23 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advising_portal', '0007_grade_remove_coursestaken_id_alter_course_created_by_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CoursesTaken',
        ),
    ]
