# Generated by Django 4.0.2 on 2022-03-23 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advising_portal', '0009_coursestaken'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CoursesTaken',
        ),
    ]
