# Generated by Django 4.0.2 on 2022-03-23 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advising_portal', '0011_coursestaken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routineslot',
            name='time_slot_id',
        ),
        migrations.AddField(
            model_name='semester',
            name='advising_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='routine_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='advising_portal.routineslot'),
        ),
    ]
