# Generated by Django 4.0.2 on 2022-03-23 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advising_portal', '0012_remove_routineslot_time_slot_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursestaken',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advising_portal.student'),
        ),
    ]
